<?php

/**
 * @Package: WordPress Plugin
 * @Subpackage: Legacy - White Label WordPress Admin Theme
 * @Since: Legacy 1.0
 * @WordPress Version: 4.0 or above
 * This file is part of Legacy - White Label WordPress Admin Theme Plugin.
 */
?>
<?php

$color1 = array(
    'primary-color' => '#f45246',
    'page-bg' => array('background-color' => '#f0f1f2'),
    'heading-color' => '#7d8a9d',
    'body-text-color' => '#7d8a9d',
    'link-color' => array('regular' => '#2a3e4c', 'hover' => '#f45246',),
    'menu-bg' => array('background-color' => '#2a3e4c'),
    'menu-color' => '#ffffff',
    'menu-hover-color' => '#ffffff',
    'submenu-color' => '#aeb2b7',
    'menu-primary-bg' => '#f45246',
    'menu-secondary-bg' => '#141c22',
    'menu-icon-line-bg' => array('background-color' => '#aeb2b7'),
    'menu-icon-color' => '#aeb2b7',
    'menu-icon-bg' => array('background-color' => '#2a3e4c'),
    'menu-active-icon-color' => '#f45246',
    'menu-active-icon-bg' => array('background-color' => '#f0f1f2'),
    'submenu-active-icon-bg' => array('background-color' => '#f45246'),
    'box-bg' => array('background-color' => '#ffffff'),
    'box-head-bg' => array('background-color' => '#64ca92'),
    'box-head-color' => '#ffffff',
    'button-primary-bg' => '#f45246',
    'button-primary-hover-bg' => '#18b3dc',
    'button-secondary-bg' => '#a9a9a9',
    'button-secondary-hover-bg' => '#999999',
    'button-text-color' => '#ffffff',
    'form-bg' => '#ffffff',
    'form-text-color' => '#7d8a9d',
    'form-border-color' => '#e2e2e4',
    'logo-bg' => '#2a3e4c',
    'topbar-menu-color' => '#ffffff',
    'topbar-menu-bg' => array('background-color' => '#18b3dc'),
    'topbar-submenu-color' => '#aeb2b7',
    'topbar-submenu-bg' => '#2a3e4c',
    'topbar-submenu-hover-bg' => '#141c22',
    'logo' => array('url' => 'PLUGINURL/images/logo.png'),
    'logo_folded' => array('url' => 'PLUGINURL/images/logo-folded.png'),
);



$color2 = array(
    'primary-color' => '#e96e4d',
    'page-bg' => array('background-color' => '#f3f4f8'),
    'heading-color' => '#7d8a9d',
    'body-text-color' => '#7d8a9d',
    'link-color' => array('regular' => '#32323a', 'hover' => '#e96e4d',),
    'menu-bg' => array('background-color' => '#32323a'),
    'menu-color' => '#ffffff',
    'menu-hover-color' => '#ffffff',
    'submenu-color' => '#aeb2b7',
    'menu-primary-bg' => '#e96e4d',
    'menu-secondary-bg' => '#212026',
    'menu-icon-line-bg' => array('background-color' => '#aeb2b7'),
    'menu-icon-color' => '#aeb2b7',
    'menu-icon-bg' => array('background-color' => '#32323a'),
    'menu-active-icon-color' => '#e96e4d',
    'menu-active-icon-bg' => array('background-color' => '#f3f4f8'),
    'submenu-active-icon-bg' => array('background-color' => '#e96e4d'),
    'box-bg' => array('background-color' => '#ffffff'),
    'box-head-bg' => array('background-color' => '#61cae7'),
    'box-head-color' => '#ffffff',
    'button-primary-bg' => '#e96e4d',
    'button-primary-hover-bg' => '#1fc7bf',
    'button-secondary-bg' => '#a9a9a9',
    'button-secondary-hover-bg' => '#999999',
    'button-text-color' => '#ffffff',
    'form-bg' => '#ffffff',
    'form-text-color' => '#7d8a9d',
    'form-border-color' => '#e2e2e4',
    'logo-bg' => '#32323a',
    'topbar-menu-color' => '#ffffff',
    'topbar-menu-bg' => array('background-color' => '#27c29c'),
    'topbar-submenu-color' => '#aeb2b7',
    'topbar-submenu-bg' => '#32323a',
    'topbar-submenu-hover-bg' => '#212026',
    'logo' => array('url' => 'PLUGINURL/images/logo.png'),
    'logo_folded' => array('url' => 'PLUGINURL/images/logo-folded.png'),
);





$color3 = array(
    'primary-color' => '#6cbdc4',
    'page-bg' => array('background-color' => '#eef1f5'),
    'heading-color' => '#7d8a9d',
    'body-text-color' => '#7d8a9d',
    'link-color' => array('regular' => '#454c50', 'hover' => '#6cbdc4',),
    'menu-bg' => array('background-color' => '#454c50'),
    'menu-color' => '#ffffff',
    'menu-hover-color' => '#ffffff',
    'submenu-color' => '#aeb2b7',
    'menu-primary-bg' => '#6cbdc4',
    'menu-secondary-bg' => '#212026',
    'menu-icon-line-bg' => array('background-color' => '#aeb2b7'),
    'menu-icon-color' => '#aeb2b7',
    'menu-icon-bg' => array('background-color' => '#454c50'),
    'menu-active-icon-color' => '#6cbdc4',
    'menu-active-icon-bg' => array('background-color' => '#eef1f5'),
    'submenu-active-icon-bg' => array('background-color' => '#6cbdc4'),
    'box-bg' => array('background-color' => '#ffffff'),
    'box-head-bg' => array('background-color' => '#ec7963'),
    'box-head-color' => '#ffffff',
    'button-primary-bg' => '#6cbdc4',
    'button-primary-hover-bg' => '#188791',
    'button-secondary-bg' => '#a9a9a9',
    'button-secondary-hover-bg' => '#999999',
    'button-text-color' => '#ffffff',
    'form-bg' => '#ffffff',
    'form-text-color' => '#7d8a9d',
    'form-border-color' => '#e2e2e4',
    'logo-bg' => '#454c50',
    'topbar-menu-color' => '#ffffff',
    'topbar-menu-bg' => array('background-color' => '#6cbdc4'),
    'topbar-submenu-color' => '#aeb2b7',
    'topbar-submenu-bg' => '#454c50',
    'topbar-submenu-hover-bg' => '#212026',
    'logo' => array('url' => 'PLUGINURL/images/logo.png'),
    'logo_folded' => array('url' => 'PLUGINURL/images/logo-folded.png'),
);



$color4 = array(
    'primary-color' => '#d76d93', //
    'page-bg' => array('background-color' => '#f1f2f7'),
    'heading-color' => '#5a5a67',
    'body-text-color' => '#5a5a67',
    'link-color' => array('regular' => '#32323a', 'hover' => '#d76d93',),
    'menu-bg' => array('background-color' => '#32323a'),
    'menu-color' => '#ffffff',
    'menu-hover-color' => '#ffffff',
    'submenu-color' => '#aeb2b7',
    'menu-primary-bg' => '#d76d93',
    'menu-secondary-bg' => '#212026',
    'menu-icon-line-bg' => array('background-color' => '#aeb2b7'),
    'menu-icon-color' => '#aeb2b7',
    'menu-icon-bg' => array('background-color' => '#32323a'),
    'menu-active-icon-color' => '#d76d93',
    'menu-active-icon-bg' => array('background-color' => '#f1f2f7'),
    'submenu-active-icon-bg' => array('background-color' => '#d76d93'),
    'box-bg' => array('background-color' => '#ffffff'),
    'box-head-bg' => array('background-color' => '#40bdbd'),
    'box-head-color' => '#ffffff',
    'button-primary-bg' => '#7d4b82',
    'button-primary-hover-bg' => '#eacc5f',
    'button-secondary-bg' => '#a9a9a9',
    'button-secondary-hover-bg' => '#999999',
    'button-text-color' => '#ffffff',
    'form-bg' => '#ffffff',
    'form-text-color' => '#5a5a67',
    'form-border-color' => '#e2e2e4',
    'logo-bg' => '#32323a',
    'topbar-menu-color' => '#ffffff',
    'topbar-menu-bg' => array('background-color' => '#7d4b82'),
    'topbar-submenu-color' => '#aeb2b7',
    'topbar-submenu-bg' => '#32323a',
    'topbar-submenu-hover-bg' => '#212026',
    'logo' => array('url' => 'PLUGINURL/images/logo.png'),
    'logo_folded' => array('url' => 'PLUGINURL/images/logo-folded.png'),
);



$color5 = array(
    'primary-color' => '#06a9d8',
    'page-bg' => array('background-color' => '#eeeff0'),
    'heading-color' => '#7d8a9d',
    'body-text-color' => '#7d8a9d',
    'link-color' => array('regular' => '#28556b', 'hover' => '#06a9d8',),
    'menu-bg' => array('background-color' => '#28556b'),
    'menu-color' => '#ffffff',
    'menu-hover-color' => '#ffffff',
    'submenu-color' => '#aeb2b7',
    'menu-primary-bg' => '#06a9d8',
    'menu-secondary-bg' => '#143444',
    'menu-icon-line-bg' => array('background-color' => '#aeb2b7'),
    'menu-icon-color' => '#aeb2b7',
    'menu-icon-bg' => array('background-color' => '#28556b'),
    'menu-active-icon-color' => '#06a9d8',
    'menu-active-icon-bg' => array('background-color' => '#eeeff0'),
    'submenu-active-icon-bg' => array('background-color' => '#06a9d8'),
    'box-bg' => array('background-color' => '#ffffff'),
    'box-head-bg' => array('background-color' => '#eab44a'),
    'box-head-color' => '#ffffff',
    'button-primary-bg' => '#06a9d8',
    'button-primary-hover-bg' => '#188791',
    'button-secondary-bg' => '#a9a9a9',
    'button-secondary-hover-bg' => '#999999',
    'button-text-color' => '#ffffff',
    'form-bg' => '#ffffff',
    'form-text-color' => '#7d8a9d',
    'form-border-color' => '#e2e2e4',
    'logo-bg' => '#28556b',
    'topbar-menu-color' => '#ffffff',
    'topbar-menu-bg' => array('background-color' => '#06a9d8'),
    'topbar-submenu-color' => '#aeb2b7',
    'topbar-submenu-bg' => '#28556b',
    'topbar-submenu-hover-bg' => '#143444',
    'logo' => array('url' => 'PLUGINURL/images/logo.png'),
    'logo_folded' => array('url' => 'PLUGINURL/images/logo-folded.png'),
);


$color6 = array(
    'primary-color' => '#f0b270',
    'page-bg' => array('background-color' => '#f3f1ec'),
    'heading-color' => '#7d8a9d',
    'body-text-color' => '#7d8a9d',
    'link-color' => array('regular' => '#392a39', 'hover' => '#f0b270',),
    'menu-bg' => array('background-color' => '#392a39'),
    'menu-color' => '#ffffff',
    'menu-hover-color' => '#ffffff',
    'submenu-color' => '#aeb2b7',
    'menu-primary-bg' => '#f0b270',
    'menu-secondary-bg' => '#6f5f5c',
    'menu-icon-line-bg' => array('background-color' => '#aeb2b7'),
    'menu-icon-color' => '#aeb2b7',
    'menu-icon-bg' => array('background-color' => '#392a39'),
    'menu-active-icon-color' => '#f0b270',
    'menu-active-icon-bg' => array('background-color' => '#f3f1ec'),
    'submenu-active-icon-bg' => array('background-color' => '#f0b270'),
    'box-bg' => array('background-color' => '#ffffff'),
    'box-head-bg' => array('background-color' => '#e38f71'),
    'box-head-color' => '#ffffff',
    'button-primary-bg' => '#f0b270',
    'button-primary-hover-bg' => '#825d5b',
    'button-secondary-bg' => '#a9a9a9',
    'button-secondary-hover-bg' => '#999999',
    'button-text-color' => '#ffffff',
    'form-bg' => '#ffffff',
    'form-text-color' => '#7d8a9d',
    'form-border-color' => '#e2e2e4',
    'logo-bg' => '#392a39',
    'topbar-menu-color' => '#ffffff',
    'topbar-menu-bg' => array('background-color' => '#825d5b'),
    'topbar-submenu-color' => '#aeb2b7',
    'topbar-submenu-bg' => '#392a39',
    'topbar-submenu-hover-bg' => '#6f5f5c',
    'logo' => array('url' => 'PLUGINURL/images/logo.png'),
    'logo_folded' => array('url' => 'PLUGINURL/images/logo-folded.png'),
);




$color7 = array(
    'primary-color' => '#f9d36a',
    'page-bg' => array('background-color' => '#ecedec'),
    'heading-color' => '#7d8a9d',
    'body-text-color' => '#7d8a9d',
    'link-color' => array('regular' => '#4c4c4d', 'hover' => '#f9d36a',),
    'menu-bg' => array('background-color' => '#4c4c4d'),
    'menu-color' => '#ffffff',
    'menu-hover-color' => '#ffffff',
    'submenu-color' => '#aeb2b7',
    'menu-primary-bg' => '#f9d36a',
    'menu-secondary-bg' => '#212026',
    'menu-icon-line-bg' => array('background-color' => '#aeb2b7'),
    'menu-icon-color' => '#aeb2b7',
    'menu-icon-bg' => array('background-color' => '#4c4c4d'),
    'menu-active-icon-color' => '#f9d36a',
    'menu-active-icon-bg' => array('background-color' => '#ecedec'),
    'submenu-active-icon-bg' => array('background-color' => '#f9d36a'),
    'box-bg' => array('background-color' => '#ffffff'),
    'box-head-bg' => array('background-color' => '#b088d5'),
    'box-head-color' => '#ffffff',
    'button-primary-bg' => '#e75b3e',
    'button-primary-hover-bg' => '#188791',
    'button-secondary-bg' => '#a9a9a9',
    'button-secondary-hover-bg' => '#999999',
    'button-text-color' => '#ffffff',
    'form-bg' => '#ffffff',
    'form-text-color' => '#7d8a9d',
    'form-border-color' => '#e2e2e4',
    'logo-bg' => '#4c4c4d',
    'topbar-menu-color' => '#ffffff',
    'topbar-menu-bg' => array('background-color' => '#f9d36a'),
    'topbar-submenu-color' => '#aeb2b7',
    'topbar-submenu-bg' => '#4c4c4d',
    'topbar-submenu-hover-bg' => '#212026',
    'logo' => array('url' => 'PLUGINURL/images/logo.png'),
    'logo_folded' => array('url' => 'PLUGINURL/images/logo-folded.png'),
);



$color8 = array(
    'primary-color' => '#f49658',
    'page-bg' => array('background-color' => '#eae9e4'),
    'heading-color' => '#7d8a9d',
    'body-text-color' => '#7d8a9d',
    'link-color' => array('regular' => '#372636', 'hover' => '#f49658',),
    'menu-bg' => array('background-color' => '#372636'),
    'menu-color' => '#ffffff',
    'menu-hover-color' => '#ffffff',
    'submenu-color' => '#aeb2b7',
    'menu-primary-bg' => '#f49658',
    'menu-secondary-bg' => '#212026',
    'menu-icon-line-bg' => array('background-color' => '#aeb2b7'),
    'menu-icon-color' => '#aeb2b7',
    'menu-icon-bg' => array('background-color' => '#372636'),
    'menu-active-icon-color' => '#f49658',
    'menu-active-icon-bg' => array('background-color' => '#eae9e4'),
    'submenu-active-icon-bg' => array('background-color' => '#f49658'),
    'box-bg' => array('background-color' => '#ffffff'),
    'box-head-bg' => array('background-color' => '#e7615c'),
    'box-head-color' => '#ffffff',
    'button-primary-bg' => '#f4c152',
    'button-primary-hover-bg' => '#8d3356',
    'button-secondary-bg' => '#a9a9a9',
    'button-secondary-hover-bg' => '#999999',
    'button-text-color' => '#ffffff',
    'form-bg' => '#ffffff',
    'form-text-color' => '#7d8a9d',
    'form-border-color' => '#e2e2e4',
    'logo-bg' => '#372636',
    'topbar-menu-color' => '#ffffff',
    'topbar-menu-bg' => array('background-color' => '#f49658'),
    'topbar-submenu-color' => '#aeb2b7',
    'topbar-submenu-bg' => '#372636',
    'topbar-submenu-hover-bg' => '#212026',
    'logo' => array('url' => 'PLUGINURL/images/logo.png'),
    'logo_folded' => array('url' => 'PLUGINURL/images/logo-folded.png'),
);


$color9 = array(
    'primary-color' => '#e35b27',
    'page-bg' => array('background-color' => '#e7e7e9'),
    'heading-color' => '#404143',
    'body-text-color' => '#704143',
    'link-color' => array('regular' => '#414244', 'hover' => '#e35b27',),
    'menu-bg' => array('background-color' => '#414244'),
    'menu-color' => '#ffffff',
    'menu-hover-color' => '#ffffff',
    'submenu-color' => '#aeb2b7',
    'menu-primary-bg' => '#e35b27',
    'menu-secondary-bg' => '#5e5f61',
    'menu-icon-line-bg' => array('background-color' => '#aeb2b7'),
    'menu-icon-color' => '#aeb2b7',
    'menu-icon-bg' => array('background-color' => '#414244'),
    'menu-active-icon-color' => '#e35b27',
    'menu-active-icon-bg' => array('background-color' => '#e7e7e9'),
    'submenu-active-icon-bg' => array('background-color' => '#e35b27'),
    'box-bg' => array('background-color' => '#ffffff'),
    'box-head-bg' => array('background-color' => '#e35b27'),
    'box-head-color' => '#ffffff',
    'button-primary-bg' => '#e35b27',
    'button-primary-hover-bg' => '#ff743d',
    'button-secondary-bg' => '#a9a9a9',
    'button-secondary-hover-bg' => '#999999',
    'button-text-color' => '#ffffff',
    'form-bg' => '#ffffff',
    'form-text-color' => '#7d8a9d',
    'form-border-color' => '#e2e2e4',
    'logo-bg' => '#414244',
    'topbar-menu-color' => '#ffffff',
    'topbar-menu-bg' => array('background-color' => '#e35b27'),
    'topbar-submenu-color' => '#aeb2b7',
    'topbar-submenu-bg' => '#414244',
    'topbar-submenu-hover-bg' => '#5e5f61',
    'logo' => array('url' => 'PLUGINURL/images/logo.png'),
    'logo_folded' => array('url' => 'PLUGINURL/images/logo-folded.png'),
);


$color10 = array(
    'primary-color' => '#5bc9c5',
    'page-bg' => array('background-color' => '#ececec'),
    'heading-color' => '#404143',
    'body-text-color' => '#704143',
    'link-color' => array('regular' => '#414244', 'hover' => '#5bc9c5',),
    'menu-bg' => array('background-color' => '#414244'),
    'menu-color' => '#ffffff',
    'menu-hover-color' => '#ffffff',
    'submenu-color' => '#aeb2b7',
    'menu-primary-bg' => '#5bc9c5',
    'menu-secondary-bg' => '#5e5f61',
    'menu-icon-line-bg' => array('background-color' => '#aeb2b7'),
    'menu-icon-color' => '#aeb2b7',
    'menu-icon-bg' => array('background-color' => '#414244'),
    'menu-active-icon-color' => '#5bc9c5',
    'menu-active-icon-bg' => array('background-color' => '#ececec'),
    'submenu-active-icon-bg' => array('background-color' => '#5bc9c5'),
    'box-bg' => array('background-color' => '#ffffff'),
    'box-head-bg' => array('background-color' => '#5bc9c5'),
    'box-head-color' => '#ffffff',
    'button-primary-bg' => '#5bc9c5',
    'button-primary-hover-bg' => '#ff743d',
    'button-secondary-bg' => '#a9a9a9',
    'button-secondary-hover-bg' => '#999999',
    'button-text-color' => '#ffffff',
    'form-bg' => '#ffffff',
    'form-text-color' => '#7d8a9d',
    'form-border-color' => '#e2e2e4',
    'logo-bg' => '#414244',
    'topbar-menu-color' => '#ffffff',
    'topbar-menu-bg' => array('background-color' => '#5bc9c5'),
    'topbar-submenu-color' => '#aeb2b7',
    'topbar-submenu-bg' => '#414244',
    'topbar-submenu-hover-bg' => '#5e5f61',
    'logo' => array('url' => 'PLUGINURL/images/logo.png'),
    'logo_folded' => array('url' => 'PLUGINURL/images/logo-folded.png'),
);

$color11 = array(
    'primary-color' => '#f86759',
    'page-bg' => array('background-color' => '#ececec'),
    'heading-color' => '#404143',
    'body-text-color' => '#704143',
    'link-color' => array('regular' => '#414244', 'hover' => '#f86759',),
    'menu-bg' => array('background-color' => '#414244'),
    'menu-color' => '#ffffff',
    'menu-hover-color' => '#ffffff',
    'submenu-color' => '#aeb2b7',
    'menu-primary-bg' => '#f86759',
    'menu-secondary-bg' => '#5e5f61',
    'menu-icon-line-bg' => array('background-color' => '#aeb2b7'),
    'menu-icon-color' => '#aeb2b7',
    'menu-icon-bg' => array('background-color' => '#414244'),
    'menu-active-icon-color' => '#f86759',
    'menu-active-icon-bg' => array('background-color' => '#ececec'),
    'submenu-active-icon-bg' => array('background-color' => '#f86759'),
    'box-bg' => array('background-color' => '#ffffff'),
    'box-head-bg' => array('background-color' => '#f86759'),
    'box-head-color' => '#ffffff',
    'button-primary-bg' => '#f86759',
    'button-primary-hover-bg' => '#ff743d',
    'button-secondary-bg' => '#a9a9a9',
    'button-secondary-hover-bg' => '#999999',
    'button-text-color' => '#ffffff',
    'form-bg' => '#ffffff',
    'form-text-color' => '#7d8a9d',
    'form-border-color' => '#e2e2e4',
    'logo-bg' => '#414244',
    'topbar-menu-color' => '#ffffff',
    'topbar-menu-bg' => array('background-color' => '#f86759'),
    'topbar-submenu-color' => '#aeb2b7',
    'topbar-submenu-bg' => '#414244',
    'topbar-submenu-hover-bg' => '#5e5f61',
    'logo' => array('url' => 'PLUGINURL/images/logo.png'),
    'logo_folded' => array('url' => 'PLUGINURL/images/logo-folded.png'),
);

$color12 = array(
    'primary-color' => '#7a6a93',
    'page-bg' => array('background-color' => '#ececec'),
    'heading-color' => '#404143',
    'body-text-color' => '#704143',
    'link-color' => array('regular' => '#414244', 'hover' => '#7a6a93',),
    'menu-bg' => array('background-color' => '#414244'),
    'menu-color' => '#ffffff',
    'menu-hover-color' => '#ffffff',
    'submenu-color' => '#aeb2b7',
    'menu-primary-bg' => '#7a6a93',
    'menu-secondary-bg' => '#5e5f61',
    'menu-icon-line-bg' => array('background-color' => '#aeb2b7'),
    'menu-icon-color' => '#aeb2b7',
    'menu-icon-bg' => array('background-color' => '#414244'),
    'menu-active-icon-color' => '#7a6a93',
    'menu-active-icon-bg' => array('background-color' => '#ececec'),
    'submenu-active-icon-bg' => array('background-color' => '#7a6a93'),
    'box-bg' => array('background-color' => '#ffffff'),
    'box-head-bg' => array('background-color' => '#7a6a93'),
    'box-head-color' => '#ffffff',
    'button-primary-bg' => '#7a6a93',
    'button-primary-hover-bg' => '#ff743d',
    'button-secondary-bg' => '#a9a9a9',
    'button-secondary-hover-bg' => '#999999',
    'button-text-color' => '#ffffff',
    'form-bg' => '#ffffff',
    'form-text-color' => '#7d8a9d',
    'form-border-color' => '#e2e2e4',
    'logo-bg' => '#414244',
    'topbar-menu-color' => '#ffffff',
    'topbar-menu-bg' => array('background-color' => '#7a6a93'),
    'topbar-submenu-color' => '#aeb2b7',
    'topbar-submenu-bg' => '#414244',
    'topbar-submenu-hover-bg' => '#5e5f61',
    'logo' => array('url' => 'PLUGINURL/images/logo.png'),
    'logo_folded' => array('url' => 'PLUGINURL/images/logo-folded.png'),
);



$color13 = array(
    'primary-color' => '#7a6a93',
    'page-bg' => array('background-color' => '#eef1f5'),
    'heading-color' => '#7d8a9d',
    'body-text-color' => '#7d8a9d',
    'link-color' => array('regular' => '#454c50', 'hover' => '#7a6a93',),
    'menu-bg' => array('background-color' => '#454c50'),
    'menu-color' => '#ffffff',
    'menu-hover-color' => '#ffffff',
    'submenu-color' => '#aeb2b7',
    'menu-primary-bg' => '#7a6a93',
    'menu-secondary-bg' => '#212026',
    'menu-icon-line-bg' => array('background-color' => '#aeb2b7'),
    'menu-icon-color' => '#aeb2b7',
    'menu-icon-bg' => array('background-color' => '#454c50'),
    'menu-active-icon-color' => '#7a6a93',
    'menu-active-icon-bg' => array('background-color' => '#eef1f5'),
    'submenu-active-icon-bg' => array('background-color' => '#7a6a93'),
    'box-bg' => array('background-color' => '#ffffff'),
    'box-head-bg' => array('background-color' => '#5bc9c5'),
    'box-head-color' => '#ffffff',
    'button-primary-bg' => '#7a6a93',
    'button-primary-hover-bg' => '#188791',
    'button-secondary-bg' => '#a9a9a9',
    'button-secondary-hover-bg' => '#999999',
    'button-text-color' => '#ffffff',
    'form-bg' => '#ffffff',
    'form-text-color' => '#7d8a9d',
    'form-border-color' => '#e2e2e4',
    'logo-bg' => '#454c50',
    'topbar-menu-color' => '#ffffff',
    'topbar-menu-bg' => array('background-color' => '#7a6a93'),
    'topbar-submenu-color' => '#aeb2b7',
    'topbar-submenu-bg' => '#454c50',
    'topbar-submenu-hover-bg' => '#212026',
    'logo' => array('url' => 'PLUGINURL/images/logo.png'),
    'logo_folded' => array('url' => 'PLUGINURL/images/logo-folded.png'),
);




$color14 = array(
    'primary-color' => '#705788',
    'page-bg' => array('background-color' => '#eef1f5'),
    'heading-color' => '#7d8a9d',
    'body-text-color' => '#7d8a9d',
    'link-color' => array('regular' => '#454c50', 'hover' => '#705788',),
    'menu-bg' => array('background-color' => '#454c50'),
    'menu-color' => '#ffffff',
    'menu-hover-color' => '#ffffff',
    'submenu-color' => '#aeb2b7',
    'menu-primary-bg' => '#705788',
    'menu-secondary-bg' => '#212026',
    'menu-icon-line-bg' => array('background-color' => '#aeb2b7'),
    'menu-icon-color' => '#aeb2b7',
    'menu-icon-bg' => array('background-color' => '#454c50'),
    'menu-active-icon-color' => '#705788',
    'menu-active-icon-bg' => array('background-color' => '#eef1f5'),
    'submenu-active-icon-bg' => array('background-color' => '#705788'),
    'box-bg' => array('background-color' => '#ffffff'),
    'box-head-bg' => array('background-color' => '#f8c866'),
    'box-head-color' => '#ffffff',
    'button-primary-bg' => '#705788',
    'button-primary-hover-bg' => '#188791',
    'button-secondary-bg' => '#a9a9a9',
    'button-secondary-hover-bg' => '#999999',
    'button-text-color' => '#ffffff',
    'form-bg' => '#ffffff',
    'form-text-color' => '#7d8a9d',
    'form-border-color' => '#e2e2e4',
    'logo-bg' => '#454c50',
    'topbar-menu-color' => '#ffffff',
    'topbar-menu-bg' => array('background-color' => '#705788'),
    'topbar-submenu-color' => '#aeb2b7',
    'topbar-submenu-bg' => '#454c50',
    'topbar-submenu-hover-bg' => '#212026',
    'logo' => array('url' => 'PLUGINURL/images/logo.png'),
    'logo_folded' => array('url' => 'PLUGINURL/images/logo-folded.png'),
);


$color15 = array(
    'primary-color' => '#f25145',
    'page-bg' => array('background-color' => '#eef1f5'),
    'heading-color' => '#7d8a9d',
    'body-text-color' => '#7d8a9d',
    'link-color' => array('regular' => '#454c50', 'hover' => '#f25145',),
    'menu-bg' => array('background-color' => '#454c50'),
    'menu-color' => '#ffffff',
    'menu-hover-color' => '#ffffff',
    'submenu-color' => '#aeb2b7',
    'menu-primary-bg' => '#f25145',
    'menu-secondary-bg' => '#212026',
    'menu-icon-line-bg' => array('background-color' => '#aeb2b7'),
    'menu-icon-color' => '#aeb2b7',
    'menu-icon-bg' => array('background-color' => '#454c50'),
    'menu-active-icon-color' => '#f25145',
    'menu-active-icon-bg' => array('background-color' => '#eef1f5'),
    'submenu-active-icon-bg' => array('background-color' => '#f25145'),
    'box-bg' => array('background-color' => '#ffffff'),
    'box-head-bg' => array('background-color' => '#283c4b'),
    'box-head-color' => '#ffffff',
    'button-primary-bg' => '#f25145',
    'button-primary-hover-bg' => '#188791',
    'button-secondary-bg' => '#a9a9a9',
    'button-secondary-hover-bg' => '#999999',
    'button-text-color' => '#ffffff',
    'form-bg' => '#ffffff',
    'form-text-color' => '#7d8a9d',
    'form-border-color' => '#e2e2e4',
    'logo-bg' => '#454c50',
    'topbar-menu-color' => '#ffffff',
    'topbar-menu-bg' => array('background-color' => '#f25145'),
    'topbar-submenu-color' => '#aeb2b7',
    'topbar-submenu-bg' => '#454c50',
    'topbar-submenu-hover-bg' => '#212026',
    'logo' => array('url' => 'PLUGINURL/images/logo.png'),
    'logo_folded' => array('url' => 'PLUGINURL/images/logo-folded.png'),
);



$color16 = array(
    'primary-color' => '#3faa96',
    'page-bg' => array('background-color' => '#eef1f5'),
    'heading-color' => '#7d8a9d',
    'body-text-color' => '#7d8a9d',
    'link-color' => array('regular' => '#454c50', 'hover' => '#3faa96',),
    'menu-bg' => array('background-color' => '#454c50'),
    'menu-color' => '#ffffff',
    'menu-hover-color' => '#ffffff',
    'submenu-color' => '#aeb2b7',
    'menu-primary-bg' => '#3faa96',
    'menu-secondary-bg' => '#212026',
    'menu-icon-line-bg' => array('background-color' => '#aeb2b7'),
    'menu-icon-color' => '#aeb2b7',
    'menu-icon-bg' => array('background-color' => '#454c50'),
    'menu-active-icon-color' => '#3faa96',
    'menu-active-icon-bg' => array('background-color' => '#eef1f5'),
    'submenu-active-icon-bg' => array('background-color' => '#3faa96'),
    'box-bg' => array('background-color' => '#ffffff'),
    'box-head-bg' => array('background-color' => '#f8c866'),
    'box-head-color' => '#ffffff',
    'button-primary-bg' => '#3faa96',
    'button-primary-hover-bg' => '#188791',
    'button-secondary-bg' => '#a9a9a9',
    'button-secondary-hover-bg' => '#999999',
    'button-text-color' => '#ffffff',
    'form-bg' => '#ffffff',
    'form-text-color' => '#7d8a9d',
    'form-border-color' => '#e2e2e4',
    'logo-bg' => '#454c50',
    'topbar-menu-color' => '#ffffff',
    'topbar-menu-bg' => array('background-color' => '#3faa96'),
    'topbar-submenu-color' => '#aeb2b7',
    'topbar-submenu-bg' => '#454c50',
    'topbar-submenu-hover-bg' => '#212026',
    'logo' => array('url' => 'PLUGINURL/images/logo.png'),
    'logo_folded' => array('url' => 'PLUGINURL/images/logo-folded.png'),
);




$color17 = array(
    'primary-color' => '#ff8053',
    'page-bg' => array('background-color' => '#eef1f5'),
    'heading-color' => '#7d8a9d',
    'body-text-color' => '#7d8a9d',
    'link-color' => array('regular' => '#454c50', 'hover' => '#ff8053',),
    'menu-bg' => array('background-color' => '#454c50'),
    'menu-color' => '#ffffff',
    'menu-hover-color' => '#ffffff',
    'submenu-color' => '#aeb2b7',
    'menu-primary-bg' => '#ff8053',
    'menu-secondary-bg' => '#212026',
    'menu-icon-line-bg' => array('background-color' => '#aeb2b7'),
    'menu-icon-color' => '#aeb2b7',
    'menu-icon-bg' => array('background-color' => '#454c50'),
    'menu-active-icon-color' => '#ff8053',
    'menu-active-icon-bg' => array('background-color' => '#eef1f5'),
    'submenu-active-icon-bg' => array('background-color' => '#ff8053'),
    'box-bg' => array('background-color' => '#ffffff'),
    'box-head-bg' => array('background-color' => '#888bb6'),
    'box-head-color' => '#ffffff',
    'button-primary-bg' => '#ff8053',
    'button-primary-hover-bg' => '#188791',
    'button-secondary-bg' => '#a9a9a9',
    'button-secondary-hover-bg' => '#999999',
    'button-text-color' => '#ffffff',
    'form-bg' => '#ffffff',
    'form-text-color' => '#7d8a9d',
    'form-border-color' => '#e2e2e4',
    'logo-bg' => '#454c50',
    'topbar-menu-color' => '#ffffff',
    'topbar-menu-bg' => array('background-color' => '#ff8053'),
    'topbar-submenu-color' => '#aeb2b7',
    'topbar-submenu-bg' => '#454c50',
    'topbar-submenu-hover-bg' => '#212026',
    'logo' => array('url' => 'PLUGINURL/images/logo.png'),
    'logo_folded' => array('url' => 'PLUGINURL/images/logo-folded.png'),
);


$color18 = array(
    'primary-color' => '#1fb5ac',
    'page-bg' => array('background-color' => '#eef1f5'),
    'heading-color' => '#7d8a9d',
    'body-text-color' => '#7d8a9d',
    'link-color' => array('regular' => '#454c50', 'hover' => '#1fb5ac',),
    'menu-bg' => array('background-color' => '#454c50'),
    'menu-color' => '#ffffff',
    'menu-hover-color' => '#ffffff',
    'submenu-color' => '#aeb2b7',
    'menu-primary-bg' => '#1fb5ac',
    'menu-secondary-bg' => '#212026',
    'menu-icon-line-bg' => array('background-color' => '#aeb2b7'),
    'menu-icon-color' => '#aeb2b7',
    'menu-icon-bg' => array('background-color' => '#454c50'),
    'menu-active-icon-color' => '#1fb5ac',
    'menu-active-icon-bg' => array('background-color' => '#eef1f5'),
    'submenu-active-icon-bg' => array('background-color' => '#1fb5ac'),
    'box-bg' => array('background-color' => '#ffffff'),
    'box-head-bg' => array('background-color' => '#9972b5'),
    'box-head-color' => '#ffffff',
    'button-primary-bg' => '#1fb5ac',
    'button-primary-hover-bg' => '#188791',
    'button-secondary-bg' => '#a9a9a9',
    'button-secondary-hover-bg' => '#999999',
    'button-text-color' => '#ffffff',
    'form-bg' => '#ffffff',
    'form-text-color' => '#7d8a9d',
    'form-border-color' => '#e2e2e4',
    'logo-bg' => '#454c50',
    'topbar-menu-color' => '#ffffff',
    'topbar-menu-bg' => array('background-color' => '#1fb5ac'),
    'topbar-submenu-color' => '#aeb2b7',
    'topbar-submenu-bg' => '#454c50',
    'topbar-submenu-hover-bg' => '#212026',
    'logo' => array('url' => 'PLUGINURL/images/logo.png'),
    'logo_folded' => array('url' => 'PLUGINURL/images/logo-folded.png'),
);


$color19 = array(
    'primary-color' => '#e1615d',
    'page-bg' => array('background-color' => '#eef1f5'),
    'heading-color' => '#7d8a9d',
    'body-text-color' => '#7d8a9d',
    'link-color' => array('regular' => '#454c50', 'hover' => '#e1615d',),
    'menu-bg' => array('background-color' => '#454c50'),
    'menu-color' => '#ffffff',
    'menu-hover-color' => '#ffffff',
    'submenu-color' => '#aeb2b7',
    'menu-primary-bg' => '#e1615d',
    'menu-secondary-bg' => '#212026',
    'menu-icon-line-bg' => array('background-color' => '#aeb2b7'),
    'menu-icon-color' => '#aeb2b7',
    'menu-icon-bg' => array('background-color' => '#454c50'),
    'menu-active-icon-color' => '#e1615d',
    'menu-active-icon-bg' => array('background-color' => '#eef1f5'),
    'submenu-active-icon-bg' => array('background-color' => '#e1615d'),
    'box-bg' => array('background-color' => '#ffffff'),
    'box-head-bg' => array('background-color' => '#fdbd57'),
    'box-head-color' => '#ffffff',
    'button-primary-bg' => '#e1615d',
    'button-primary-hover-bg' => '#188791',
    'button-secondary-bg' => '#a9a9a9',
    'button-secondary-hover-bg' => '#999999',
    'button-text-color' => '#ffffff',
    'form-bg' => '#ffffff',
    'form-text-color' => '#7d8a9d',
    'form-border-color' => '#e2e2e4',
    'logo-bg' => '#454c50',
    'topbar-menu-color' => '#ffffff',
    'topbar-menu-bg' => array('background-color' => '#e1615d'),
    'topbar-submenu-color' => '#aeb2b7',
    'topbar-submenu-bg' => '#454c50',
    'topbar-submenu-hover-bg' => '#212026',
    'logo' => array('url' => 'PLUGINURL/images/logo.png'),
    'logo_folded' => array('url' => 'PLUGINURL/images/logo-folded.png'),
);


$color20 = array(
    'primary-color' => '#f17e56',
    'page-bg' => array('background-color' => '#eef1f5'),
    'heading-color' => '#7d8a9d',
    'body-text-color' => '#7d8a9d',
    'link-color' => array('regular' => '#454c50', 'hover' => '#f17e56',),
    'menu-bg' => array('background-color' => '#454c50'),
    'menu-color' => '#ffffff',
    'menu-hover-color' => '#ffffff',
    'submenu-color' => '#aeb2b7',
    'menu-primary-bg' => '#f17e56',
    'menu-secondary-bg' => '#212026',
    'menu-icon-line-bg' => array('background-color' => '#aeb2b7'),
    'menu-icon-color' => '#aeb2b7',
    'menu-icon-bg' => array('background-color' => '#454c50'),
    'menu-active-icon-color' => '#f17e56',
    'menu-active-icon-bg' => array('background-color' => '#eef1f5'),
    'submenu-active-icon-bg' => array('background-color' => '#f17e56'),
    'box-bg' => array('background-color' => '#ffffff'),
    'box-head-bg' => array('background-color' => '#695f56'),
    'box-head-color' => '#ffffff',
    'button-primary-bg' => '#f17e56',
    'button-primary-hover-bg' => '#188791',
    'button-secondary-bg' => '#a9a9a9',
    'button-secondary-hover-bg' => '#999999',
    'button-text-color' => '#ffffff',
    'form-bg' => '#ffffff',
    'form-text-color' => '#7d8a9d',
    'form-border-color' => '#e2e2e4',
    'logo-bg' => '#454c50',
    'topbar-menu-color' => '#ffffff',
    'topbar-menu-bg' => array('background-color' => '#f17e56'),
    'topbar-submenu-color' => '#aeb2b7',
    'topbar-submenu-bg' => '#454c50',
    'topbar-submenu-hover-bg' => '#212026',
    'logo' => array('url' => 'PLUGINURL/images/logo.png'),
    'logo_folded' => array('url' => 'PLUGINURL/images/logo-folded.png'),
);



$color21 = array(
    'primary-color' => '#1fb5ac',
    'page-bg' => array('background-color' => '#ececec'),
    'heading-color' => '#404143',
    'body-text-color' => '#704143',
    'link-color' => array('regular' => '#414244', 'hover' => '#1fb5ac',),
    'menu-bg' => array('background-color' => '#414244'),
    'menu-color' => '#ffffff',
    'menu-hover-color' => '#ffffff',
    'submenu-color' => '#aeb2b7',
    'menu-primary-bg' => '#1fb5ac',
    'menu-secondary-bg' => '#5e5f61',
    'menu-icon-line-bg' => array('background-color' => '#aeb2b7'),
    'menu-icon-color' => '#aeb2b7',
    'menu-icon-bg' => array('background-color' => '#414244'),
    'menu-active-icon-color' => '#1fb5ac',
    'menu-active-icon-bg' => array('background-color' => '#ececec'),
    'submenu-active-icon-bg' => array('background-color' => '#1fb5ac'),
    'box-bg' => array('background-color' => '#ffffff'),
    'box-head-bg' => array('background-color' => '#1fb5ac'),
    'box-head-color' => '#ffffff',
    'button-primary-bg' => '#1fb5ac',
    'button-primary-hover-bg' => '#ff743d',
    'button-secondary-bg' => '#a9a9a9',
    'button-secondary-hover-bg' => '#999999',
    'button-text-color' => '#ffffff',
    'form-bg' => '#ffffff',
    'form-text-color' => '#7d8a9d',
    'form-border-color' => '#e2e2e4',
    'logo-bg' => '#414244',
    'topbar-menu-color' => '#ffffff',
    'topbar-menu-bg' => array('background-color' => '#1fb5ac'),
    'topbar-submenu-color' => '#aeb2b7',
    'topbar-submenu-bg' => '#414244',
    'topbar-submenu-hover-bg' => '#5e5f61',
    'logo' => array('url' => 'PLUGINURL/images/logo.png'),
    'logo_folded' => array('url' => 'PLUGINURL/images/logo-folded.png'),
);


$color22 = array(
    'primary-color' => '#7a628b',
    'page-bg' => array('background-color' => '#eef1f5'),
    'heading-color' => '#7d8a9d',
    'body-text-color' => '#7d8a9d',
    'link-color' => array('regular' => '#454c50', 'hover' => '#7a628b',),
    'menu-bg' => array('background-color' => '#454c50'),
    'menu-color' => '#ffffff',
    'menu-hover-color' => '#ffffff',
    'submenu-color' => '#aeb2b7',
    'menu-primary-bg' => '#7a628b',
    'menu-secondary-bg' => '#212026',
    'menu-icon-line-bg' => array('background-color' => '#aeb2b7'),
    'menu-icon-color' => '#aeb2b7',
    'menu-icon-bg' => array('background-color' => '#454c50'),
    'menu-active-icon-color' => '#7a628b',
    'menu-active-icon-bg' => array('background-color' => '#eef1f5'),
    'submenu-active-icon-bg' => array('background-color' => '#7a628b'),
    'box-bg' => array('background-color' => '#ffffff'),
    'box-head-bg' => array('background-color' => '#cd5d7b'),
    'box-head-color' => '#ffffff',
    'button-primary-bg' => '#7a628b',
    'button-primary-hover-bg' => '#188791',
    'button-secondary-bg' => '#a9a9a9',
    'button-secondary-hover-bg' => '#999999',
    'button-text-color' => '#ffffff',
    'form-bg' => '#ffffff',
    'form-text-color' => '#7d8a9d',
    'form-border-color' => '#e2e2e4',
    'logo-bg' => '#454c50',
    'topbar-menu-color' => '#ffffff',
    'topbar-menu-bg' => array('background-color' => '#7a628b'),
    'topbar-submenu-color' => '#aeb2b7',
    'topbar-submenu-bg' => '#454c50',
    'topbar-submenu-hover-bg' => '#212026',
    'logo' => array('url' => 'PLUGINURL/images/logo.png'),
    'logo_folded' => array('url' => 'PLUGINURL/images/logo-folded.png'),
);


$color23 = array(
    'primary-color' => '#34495e',
    'page-bg' => array('background-color' => '#eef1f5'),
    'heading-color' => '#7d8a9d',
    'body-text-color' => '#7d8a9d',
    'link-color' => array('regular' => '#454c50', 'hover' => '#34495e',),
    'menu-bg' => array('background-color' => '#454c50'),
    'menu-color' => '#ffffff',
    'menu-hover-color' => '#ffffff',
    'submenu-color' => '#aeb2b7',
    'menu-primary-bg' => '#34495e',
    'menu-secondary-bg' => '#212026',
    'menu-icon-line-bg' => array('background-color' => '#aeb2b7'),
    'menu-icon-color' => '#aeb2b7',
    'menu-icon-bg' => array('background-color' => '#454c50'),
    'menu-active-icon-color' => '#34495e',
    'menu-active-icon-bg' => array('background-color' => '#eef1f5'),
    'submenu-active-icon-bg' => array('background-color' => '#34495e'),
    'box-bg' => array('background-color' => '#ffffff'),
    'box-head-bg' => array('background-color' => '#1fdab5'),
    'box-head-color' => '#ffffff',
    'button-primary-bg' => '#34495e',
    'button-primary-hover-bg' => '#188791',
    'button-secondary-bg' => '#a9a9a9',
    'button-secondary-hover-bg' => '#999999',
    'button-text-color' => '#ffffff',
    'form-bg' => '#ffffff',
    'form-text-color' => '#7d8a9d',
    'form-border-color' => '#e2e2e4',
    'logo-bg' => '#454c50',
    'topbar-menu-color' => '#ffffff',
    'topbar-menu-bg' => array('background-color' => '#34495e'),
    'topbar-submenu-color' => '#aeb2b7',
    'topbar-submenu-bg' => '#454c50',
    'topbar-submenu-hover-bg' => '#212026',
    'logo' => array('url' => 'PLUGINURL/images/logo.png'),
    'logo_folded' => array('url' => 'PLUGINURL/images/logo-folded.png'),
);


$color24 = array(
    'primary-color' => '#568c98',
    'page-bg' => array('background-color' => '#eef1f5'),
    'heading-color' => '#7d8a9d',
    'body-text-color' => '#7d8a9d',
    'link-color' => array('regular' => '#454c50', 'hover' => '#568c98',),
    'menu-bg' => array('background-color' => '#454c50'),
    'menu-color' => '#ffffff',
    'menu-hover-color' => '#ffffff',
    'submenu-color' => '#aeb2b7',
    'menu-primary-bg' => '#568c98',
    'menu-secondary-bg' => '#212026',
    'menu-icon-line-bg' => array('background-color' => '#aeb2b7'),
    'menu-icon-color' => '#aeb2b7',
    'menu-icon-bg' => array('background-color' => '#454c50'),
    'menu-active-icon-color' => '#568c98',
    'menu-active-icon-bg' => array('background-color' => '#eef1f5'),
    'submenu-active-icon-bg' => array('background-color' => '#ec8e72'),
    'box-bg' => array('background-color' => '#ffffff'),
    'box-head-bg' => array('background-color' => '#ec8e72'),
    'box-head-color' => '#ffffff',
    'button-primary-bg' => '#568c98',
    'button-primary-hover-bg' => '#188791',
    'button-secondary-bg' => '#a9a9a9',
    'button-secondary-hover-bg' => '#999999',
    'button-text-color' => '#ffffff',
    'form-bg' => '#ffffff',
    'form-text-color' => '#7d8a9d',
    'form-border-color' => '#e2e2e4',
    'logo-bg' => '#454c50',
    'topbar-menu-color' => '#ffffff',
    'topbar-menu-bg' => array('background-color' => '#568c98'),
    'topbar-submenu-color' => '#aeb2b7',
    'topbar-submenu-bg' => '#454c50',
    'topbar-submenu-hover-bg' => '#212026',
    'logo' => array('url' => 'PLUGINURL/images/logo.png'),
    'logo_folded' => array('url' => 'PLUGINURL/images/logo-folded.png'),
);


$color25 = array(
    'primary-color' => '#32cf78',
    'page-bg' => array('background-color' => '#eef1f5'),
    'heading-color' => '#7d8a9d',
    'body-text-color' => '#7d8a9d',
    'link-color' => array('regular' => '#454c50', 'hover' => '#32cf78',),
    'menu-bg' => array('background-color' => '#454c50'),
    'menu-color' => '#ffffff',
    'menu-hover-color' => '#ffffff',
    'submenu-color' => '#aeb2b7',
    'menu-primary-bg' => '#32cf78',
    'menu-secondary-bg' => '#212026',
    'menu-icon-line-bg' => array('background-color' => '#aeb2b7'),
    'menu-icon-color' => '#aeb2b7',
    'menu-icon-bg' => array('background-color' => '#454c50'),
    'menu-active-icon-color' => '#32cf78',
    'menu-active-icon-bg' => array('background-color' => '#eef1f5'),
    'submenu-active-icon-bg' => array('background-color' => '#32cf78'),
    'box-bg' => array('background-color' => '#ffffff'),
    'box-head-bg' => array('background-color' => '#f25858'),
    'box-head-color' => '#ffffff',
    'button-primary-bg' => '#32cf78',
    'button-primary-hover-bg' => '#188791',
    'button-secondary-bg' => '#a9a9a9',
    'button-secondary-hover-bg' => '#999999',
    'button-text-color' => '#ffffff',
    'form-bg' => '#ffffff',
    'form-text-color' => '#7d8a9d',
    'form-border-color' => '#e2e2e4',
    'logo-bg' => '#454c50',
    'topbar-menu-color' => '#ffffff',
    'topbar-menu-bg' => array('background-color' => '#32cf78'),
    'topbar-submenu-color' => '#aeb2b7',
    'topbar-submenu-bg' => '#454c50',
    'topbar-submenu-hover-bg' => '#212026',
    'logo' => array('url' => 'PLUGINURL/images/logo.png'),
    'logo_folded' => array('url' => 'PLUGINURL/images/logo-folded.png'),
);

$GLOBALS['legacy_color']['color1'] = $color1; // dark
$GLOBALS['legacy_color']['color2'] = $color2; // modify
$GLOBALS['legacy_color']['color3'] = $color3; // dark
$GLOBALS['legacy_color']['color4'] = $color4; // light
$GLOBALS['legacy_color']['color5'] = $color5; // dark
$GLOBALS['legacy_color']['color6'] = $color6; // light
$GLOBALS['legacy_color']['color7'] = $color7; // light
$GLOBALS['legacy_color']['color8'] = $color8; // light
$GLOBALS['legacy_color']['color9'] = $color9; // dark
$GLOBALS['legacy_color']['color10'] = $color10; // dark
$GLOBALS['legacy_color']['color11'] = $color11; // dark
$GLOBALS['legacy_color']['color12'] = $color12; // dark
$GLOBALS['legacy_color']['color13'] = $color13; // dark
$GLOBALS['legacy_color']['color14'] = $color14; // dark
$GLOBALS['legacy_color']['color15'] = $color15; // dark
$GLOBALS['legacy_color']['color16'] = $color16; // dark
$GLOBALS['legacy_color']['color17'] = $color17; // light
$GLOBALS['legacy_color']['color18'] = $color18; // light
$GLOBALS['legacy_color']['color19'] = $color19; // light
$GLOBALS['legacy_color']['color20'] = $color20; // light
$GLOBALS['legacy_color']['color21'] = $color21; // light
  $GLOBALS['legacy_color']['color22'] = $color22; // light
  $GLOBALS['legacy_color']['color23'] = $color23; // light
  $GLOBALS['legacy_color']['color24'] = $color24; // light
  $GLOBALS['legacy_color']['color25'] = $color25; // light



/* List Names for options panel */
$GLOBALS['legacy_color_list']['custom'] = "Custom Theme";
$GLOBALS['legacy_color_list']['color1'] = "Theme 1";
$GLOBALS['legacy_color_list']['color2'] = "Theme 2";
$GLOBALS['legacy_color_list']['color3'] = "Theme 3";
$GLOBALS['legacy_color_list']['color4'] = "Theme 4";
$GLOBALS['legacy_color_list']['color5'] = "Theme 5";
$GLOBALS['legacy_color_list']['color6'] = "Theme 6";
$GLOBALS['legacy_color_list']['color7'] = "Theme 7";
$GLOBALS['legacy_color_list']['color8'] = "Theme 8";
$GLOBALS['legacy_color_list']['color9'] = "Theme 9";
$GLOBALS['legacy_color_list']['color10'] = "Theme 10";
$GLOBALS['legacy_color_list']['color11'] = "Theme 11"; // color1 single
$GLOBALS['legacy_color_list']['color12'] = "Theme 12"; // color1 single
$GLOBALS['legacy_color_list']['color13'] = "Theme 13"; // color1 single
$GLOBALS['legacy_color_list']['color14'] = "Theme 14"; // color2 single
$GLOBALS['legacy_color_list']['color15'] = "Theme 15"; // color2 single
$GLOBALS['legacy_color_list']['color16'] = "Theme 16"; // color2 single
$GLOBALS['legacy_color_list']['color17'] = "Theme 17"; // color3 single
$GLOBALS['legacy_color_list']['color18'] = "Theme 18"; // color3 single
$GLOBALS['legacy_color_list']['color19'] = "Theme 19";
$GLOBALS['legacy_color_list']['color20'] = "Theme 20";
$GLOBALS['legacy_color_list']['color21'] = "Theme 21";
  $GLOBALS['legacy_color_list']['color22'] = "Theme 22";
  $GLOBALS['legacy_color_list']['color23'] = "Theme 23";
  $GLOBALS['legacy_color_list']['color24'] = "Theme 24";
  $GLOBALS['legacy_color_list']['color25'] = "Theme 25";
?>